### ISSUE TITLE
problem during PortalDeployment.yml upload

### ISSUE THREAD

**Issue by ioualha** [digexp/DX.Kubernetes.IBM-Cloud#2] opened 2018-01-23 21:43 UTC
Hi,
I'm facing a problem when i try to import the PortalDeployment.yml
The error is 

> Deploying file has failed
> Unknown resource kind: List

![image](https://user-images.githubusercontent.com/5928403/35302416-b282d59a-008e-11e8-92bd-935cdca3eb7e.png)

Could you help please.

**Comment by georgefridrich** [comment] 2018-01-23 21:53
Hi, I assume your PVC deployed without issue?  Can you please confirm that and also what version of Kubernetes you are deploying to.  Is this on IBM Cloud or Private cloud or another cloud provider?  Thanks.

**Comment by ioualha** [comment] 2018-01-23 22:34
Yes the PVC is deployed without issue.
I'm using kubernetes 1.8.6 on IBM Cloud.

**Comment by georgefridrich** [comment] 2018-01-23 22:56
Hi ioualha,

We tested with 1.7.4 (confirmed) so seems it is possible the newer version of Kubes has a small issue with our deployment yaml.  I'm deploying a new kube cluster now at 1.8.6 and will recreate.  Once I do I'll patch the deployment.yaml and upload the new version here.  I should have that completed by tomorrow morning.  Thanks.

**Comment by georgefridrich** [comment] 2018-01-24 17:24
Hi, 
I was able to recreate your issue on Kubes 1.8.6.  I am working on a patch now, I will make it available asap.  Thanks.

**Comment by georgefridrich** [comment] 2018-01-24 20:01
OK I have this resolved however Kubes 1.8.6 has an issue where a simple export of a deployment fails to import.  This is likely something Kubes should address.  I redid our deployment and service yaml and both are working.  Because this is a significant change we are going to do a quick regression test on this deployment.  Please bear with us and I'll have those two new yamls uploaded to this git repo.  Thanks.

**Comment by georgefridrich** [comment] 2018-01-24 21:17
Should be all set.  Please remember to update the image path in the deployment yaml.  Thank you for bringing this to my attention.  Please let me know your results.  Cheers.

**Comment by ioualha** [comment] 2018-01-25 10:46
Thank you so much it works fine. However i have exceeded the pull traffic quota for the current month. I have to upgrade the free plan. Regards.

**Comment by ioualha** [comment] 2018-01-25 12:28
I upgraded to standard plan.
but i get this error
/root/./checkProfile.sh: line 12: syntax error: unexpected end of file

**Comment by georgefridrich** [comment] 2018-01-25 16:14
Hi ioualha,
We'll get this resolved quickly for you.  We are attempting to recreate now and if necessary we'll patch the shell script.  Thanks.

**Comment by georgefridrich** [comment] 2018-01-25 20:18
Hi ioualha,
We have been unable to recreate your error.  We have tried multiple paths of cloning the git repo, all result in an image that can be built without error.   Could you provide us with additional information: 1) How are you cloning the git repo? 2) Where/when are you experiencing this error and is there any attempt to modify that script?  Line 12 is blank so it may be removed without issue however this has not been an issue in our testing.  Thanks.

**Comment by ioualha** [comment] 2018-01-25 21:51
Hi,
1) git clone
2) When i upload the deployment yml i did not modify the checkProfile script

when i use the kubectl apply -f PortalDeployment.yml
I get this message

> error: error validating "PortalDeployment.yml": error validating data: [ValidationError(Deployment.spec.template.spec.volumes[0]): unknown field "resources" in io.k8s.api.core.v1.Volume, ValidationError(Deployment.spec.template.spec.volumes[0]): unknown field "terminationMessagePath" in io.k8s.api.core.v1.Volume, ValidationError(Deployment.spec.template.spec.volumes[0]): unknown field "terminationMessagePolicy" in io.k8s.api.core.v1.Volume]; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by georgefridrich** [comment] 2018-01-25 22:09
OK, that is a different error but I will look into it.  We are deploying the yamls via the Kubes Dashboard (proxy) so it could be that cmd line path is running validation that we don't get otherwise.  Those are values I set specifically for our PVC and were required in 1.7.4.  Could be they are no longer required and I can remove them.  I will investigate and attempt to recreate by deploying via kubectl first thing tomorrow morning and let you know what I find.  Thanks.

**Comment by ioualha** [comment] 2018-01-25 22:54
I used also the kubernetes dashboard to upload file

but few minutes later i get this

![image](https://user-images.githubusercontent.com/5928403/35416752-98123564-022a-11e8-9414-6a49b91a2585.png)

![image](https://user-images.githubusercontent.com/5928403/35416851-0daed426-022b-11e8-9479-db9cafe56b23.png)

Thanks for your help

**Comment by georgefridrich** [comment] 2018-01-25 22:59
That tells me there is something likely wrong with your image.  If you go to the pods view and select it, click on the upper left corner menu and select logs.  Please paste what you see there.  Thanks.  (I will still resolve the validation errors when deploying via cml line.)

**Comment by ioualha** [comment] 2018-01-26 07:34
your right some thing wrong with the image. when i run it locally i get the same error.
I deleted the checkProfile.sh from the docker file. After a rebuild the container starts without issues.
but when i republish the new image to IBM Cloud i still have the same problem as below

![image](https://user-images.githubusercontent.com/5928403/35429106-de3c6aee-0272-11e8-88d2-b40f44a57a14.png)

**Comment by georgefridrich** [comment] 2018-01-26 16:29
Hi ioualha,
Can you provide us with the Docker version you are using and what OS you are on?  We have multiple folks using this git repo and no one yet has had this issue you are seeing with the checkprofile script.  Wondering if it might have something to do with your Docker version.
If you could please also send me the chechProfile.sh you are using via email, fridrich@us.ibm.com.
I just want to diff against our own clone download.  Thanks.

**Comment by georgefridrich** [comment] 2018-02-09 21:33
[checkProfile.tar.gz](https://github.com/digexp/DX.Kubernetes.IBM-Cloud/files/1712476/checkProfile.tar.gz)

**Comment by georgefridrich** [comment] 2018-03-05 20:15
Going to close this now that we are all set.  I uploaded a new script that has a bit more detail about what we are doing during the volume copy.  Also, when uploading a new image with the same name, the container repository in IBM Cloud will cache image layers so to be on the safe side, rm the CR dir for the image that will be replaced.  Thanks.

**Closed as completed by georgefridrich** 2018-03-05 20:15 UTC
